// Package mysql provides a MySQL implementation of db.Database.
package mysql

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/ernestoponce27/db-tui/internal/db"
	"github.com/ernestoponce27/db-tui/internal/logger"
	mysqldriver "github.com/go-sql-driver/mysql"
)

const listTablesSQL = `
	SELECT table_name
	FROM information_schema.tables
	WHERE table_schema = DATABASE()
		AND table_type = 'BASE TABLE'
	ORDER BY table_name`

type mysqlDatabase struct {
	database *sql.DB
	logger   *logger.Logger
	config   *mysqldriver.Config
}

// Connect opens a MySQL database using dsn and verifies that it is reachable.
//
// Both go-sql-driver/mysql DSNs and mysql:// URLs are accepted. URL-form DSNs
// are useful for connection settings generated by the TUI.
func Connect(ctx context.Context, dsn string) (db.Database, error) {
	driverConfig, err := parseDSN(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse MySQL DSN: %w", err)
	}

	queryLogger, err := logger.Open()
	if err != nil {
		return nil, fmt.Errorf("open query log: %w", err)
	}

	connector, err := mysqldriver.NewConnector(driverConfig)
	if err != nil {
		_ = queryLogger.Close()
		return nil, fmt.Errorf("create MySQL connector: %w", err)
	}
	database := sql.OpenDB(connector)
	if err := database.PingContext(ctx); err != nil {
		_ = database.Close()
		_ = queryLogger.Close()
		return nil, fmt.Errorf("connect to MySQL: %w", err)
	}

	return &mysqlDatabase{database: database, logger: queryLogger, config: driverConfig}, nil
}

func parseDSN(dsn string) (*mysqldriver.Config, error) {
	dsn = strings.TrimSpace(dsn)
	if !strings.HasPrefix(strings.ToLower(dsn), "mysql://") {
		config, err := mysqldriver.ParseDSN(dsn)
		if err != nil {
			return nil, err
		}
		if strings.TrimSpace(config.DBName) == "" {
			return nil, errors.New("database name is required")
		}
		return config, nil
	}

	parsed, err := url.Parse(dsn)
	if err != nil {
		return nil, err
	}
	if parsed.Scheme != "mysql" {
		return nil, fmt.Errorf("unsupported scheme %q", parsed.Scheme)
	}
	if parsed.User == nil || parsed.User.Username() == "" {
		return nil, errors.New("username is required")
	}
	if parsed.Hostname() == "" {
		return nil, errors.New("host is required")
	}

	databaseName := strings.TrimPrefix(parsed.Path, "/")
	if databaseName == "" {
		return nil, errors.New("database name is required")
	}
	if strings.Contains(databaseName, "/") {
		return nil, errors.New("database name cannot contain a slash")
	}

	port := parsed.Port()
	if port == "" {
		port = "3306"
	}
	portNumber, err := strconv.Atoi(port)
	if err != nil || portNumber < 1 || portNumber > 65535 {
		return nil, errors.New("port must be between 1 and 65535")
	}

	password, _ := parsed.User.Password()
	config := mysqldriver.NewConfig()
	config.User = parsed.User.Username()
	config.Passwd = password
	config.Net = "tcp"
	config.Addr = net.JoinHostPort(parsed.Hostname(), port)
	config.DBName = databaseName

	if parsed.RawQuery != "" {
		return mysqldriver.ParseDSN(config.FormatDSN() + "?" + parsed.RawQuery)
	}
	return config, nil
}

// Name returns the configured MySQL database name.
func (m *mysqlDatabase) Name() string {
	return m.config.DBName
}

// ListTables returns the base tables in the connected MySQL database.
func (m *mysqlDatabase) ListTables(ctx context.Context) ([]db.Table, error) {
	m.logger.Log(listTablesSQL)
	rows, err := m.database.QueryContext(ctx, listTablesSQL)
	if err != nil {
		return nil, fmt.Errorf("query MySQL tables: %w", err)
	}
	defer rows.Close()

	tables := make([]db.Table, 0)
	for rows.Next() {
		var table db.Table
		if err := rows.Scan(&table.Name); err != nil {
			return nil, fmt.Errorf("scan MySQL table: %w", err)
		}
		tables = append(tables, table)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate MySQL tables: %w", err)
	}
	return tables, nil
}

// GetRows returns an unordered page of rows from a MySQL table.
func (m *mysqlDatabase) GetRows(ctx context.Context, table db.Table, page db.PageRequest) (db.RowPage, error) {
	if table.Name == "" {
		return db.RowPage{}, errors.New("table name is required")
	}
	if page.Offset < 0 {
		return db.RowPage{}, errors.New("page offset cannot be negative")
	}
	if page.Limit < 1 || page.Limit > db.MaxPageSize {
		return db.RowPage{}, fmt.Errorf("page limit must be between 1 and %d", db.MaxPageSize)
	}

	tableName := quoteIdentifier(table.Name)
	queryLimit := page.Limit + 1
	query := fmt.Sprintf("SELECT * FROM %s LIMIT ? OFFSET ?", tableName)
	m.logger.Log(fmt.Sprintf("SELECT * FROM %s LIMIT %d OFFSET %d", tableName, queryLimit, page.Offset))
	rows, err := m.database.QueryContext(ctx, query, queryLimit, page.Offset)
	if err != nil {
		return db.RowPage{}, fmt.Errorf("query MySQL rows: %w", err)
	}
	defer rows.Close()

	columns, err := rows.Columns()
	if err != nil {
		return db.RowPage{}, fmt.Errorf("read MySQL columns: %w", err)
	}
	columnTypes, err := rows.ColumnTypes()
	if err != nil {
		return db.RowPage{}, fmt.Errorf("read MySQL column types: %w", err)
	}
	result := db.RowPage{Columns: columns}
	for rows.Next() {
		values, err := scanRow(rows, columnTypes)
		if err != nil {
			return db.RowPage{}, fmt.Errorf("read MySQL row: %w", err)
		}
		result.Rows = append(result.Rows, values)
	}
	if err := rows.Err(); err != nil {
		return db.RowPage{}, fmt.Errorf("iterate MySQL rows: %w", err)
	}

	if len(result.Rows) > page.Limit {
		result.HasMore = true
		result.Rows = result.Rows[:page.Limit]
	}
	return result, nil
}

// Execute runs arbitrary SQL and returns its first 100 rows and command status.
func (m *mysqlDatabase) Execute(ctx context.Context, statement string) (db.QueryResult, error) {
	m.logger.Log(statement)
	rows, err := m.database.QueryContext(ctx, statement)
	if err != nil {
		return db.QueryResult{}, fmt.Errorf("execute MySQL query: %w", err)
	}
	defer rows.Close()

	columns, err := rows.Columns()
	if err != nil {
		return db.QueryResult{}, fmt.Errorf("read MySQL query columns: %w", err)
	}
	columnTypes, err := rows.ColumnTypes()
	if err != nil {
		return db.QueryResult{}, fmt.Errorf("read MySQL query column types: %w", err)
	}
	result := db.QueryResult{
		Columns:    columns,
		CommandTag: commandTag(statement),
	}
	for rows.Next() {
		if len(result.Rows) == db.MaxQueryResultRows {
			break
		}
		values, err := scanRow(rows, columnTypes)
		if err != nil {
			return db.QueryResult{}, fmt.Errorf("read MySQL query row: %w", err)
		}
		result.Rows = append(result.Rows, values)
	}
	if err := rows.Close(); err != nil {
		return db.QueryResult{}, fmt.Errorf("close MySQL query rows: %w", err)
	}
	if err := rows.Err(); err != nil {
		return db.QueryResult{}, fmt.Errorf("iterate MySQL query rows: %w", err)
	}
	return result, nil
}

func scanRow(rows *sql.Rows, columnTypes []*sql.ColumnType) ([]any, error) {
	values := make([]any, len(columnTypes))
	destinations := make([]any, len(values))
	for index := range values {
		destinations[index] = &values[index]
	}
	if err := rows.Scan(destinations...); err != nil {
		return nil, err
	}
	for index, value := range values {
		bytes, ok := value.([]byte)
		if !ok {
			continue
		}
		dataType := strings.ToUpper(columnTypes[index].DatabaseTypeName())
		if strings.Contains(dataType, "BLOB") ||
			strings.Contains(dataType, "BINARY") ||
			dataType == "BIT" ||
			dataType == "GEOMETRY" {
			values[index] = append([]byte(nil), bytes...)
		} else {
			values[index] = string(bytes)
		}
	}
	return values, nil
}

func quoteIdentifier(identifier string) string {
	return "`" + strings.ReplaceAll(identifier, "`", "``") + "`"
}

func commandTag(statement string) string {
	fields := strings.Fields(statement)
	if len(fields) == 0 {
		return ""
	}
	command := strings.ToUpper(strings.Trim(fields[0], "();"))
	if (command == "CREATE" || command == "ALTER" || command == "DROP") && len(fields) > 1 {
		index := 1
		if command == "CREATE" && strings.EqualFold(strings.Trim(fields[index], "();"), "TEMPORARY") && len(fields) > 2 {
			index++
		}
		return command + " " + strings.ToUpper(strings.Trim(fields[index], "();`"))
	}
	return command
}

// Dump writes the connected database to a timestamped SQL file using mysqldump.
func (m *mysqlDatabase) Dump(ctx context.Context) error {
	filename := safeFilename(m.config.DBName) + "_" + time.Now().Format("20060102_150405") + ".sql"
	args := []string{"--user=" + m.config.User, "--result-file=" + filename, "--single-transaction"}

	switch m.config.Net {
	case "", "tcp", "tcp4", "tcp6":
		host, port, err := net.SplitHostPort(m.config.Addr)
		if err != nil {
			return fmt.Errorf("parse MySQL address: %w", err)
		}
		args = append(args, "--protocol=tcp", "--host="+host, "--port="+port)
	case "unix":
		args = append(args, "--socket="+m.config.Addr)
	default:
		return fmt.Errorf("unsupported MySQL network %q for dump", m.config.Net)
	}
	args = append(args, m.config.DBName)

	command := exec.CommandContext(ctx, "mysqldump", args...)
	if m.config.Passwd != "" {
		command.Env = append(os.Environ(), "MYSQL_PWD="+m.config.Passwd)
	}
	output, err := command.CombinedOutput()
	if err != nil {
		_ = os.Remove(filename)
		return fmt.Errorf("mysqldump: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func safeFilename(name string) string {
	name = filepath.Base(strings.TrimSpace(name))
	name = strings.Map(func(character rune) rune {
		switch {
		case character >= 'a' && character <= 'z':
			return character
		case character >= 'A' && character <= 'Z':
			return character
		case character >= '0' && character <= '9':
			return character
		case character == '-', character == '_', character == '.':
			return character
		default:
			return '_'
		}
	}, name)
	if strings.Trim(name, ".") == "" {
		return "mysql"
	}
	return name
}

// Close releases all connections held by the database.
func (m *mysqlDatabase) Close() {
	_ = m.database.Close()
	_ = m.logger.Close()
}

var _ db.Database = (*mysqlDatabase)(nil)
